services:
  application:
    container_name: ddareungi-service
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    networks:
      - ddareungi-net
  ### REDIS ###
  redis_ddareungi:
    image: redis
    container_name: ddareungi-redis
    ports:
      - "6379:6379"
    networks:
      - ddareungi-net


networks:
  ddareungi-net:
